### ISSUE TITLE
Rasa Server Error

### ISSUE THREAD

**Issue by miracle10240** [s-4-m-a-n/RestaurantBot#5]
I am leeyamkeng and this project looks awesome.
I wanted to run it on my local computer but it didn't work.
How can I solve this?  I followed your instructions but it was still not working.
Please help me. I will wait for your reply.
Thanks.
Lee
![image](https://github.com/s-4-m-a-n/RestaurantBot/assets/147319725/b06bfe79-aae8-4fa5-8baa-4e7a2c8996e1)
![image (1)](https://github.com/s-4-m-a-n/RestaurantBot/assets/147319725/ef2c958c-330e-4a64-90b4-4a7f07371f0e)

**Comment by s-4-m-a-n** [comment]
please use docker

**Comment by miracle10240** [comment]
Thank you for your reply.
I used docker but still not working.

**Comment by s-4-m-a-n** [comment]
Can you show me the screenshot of the error message ?
